name: Clang-Tidy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  tidy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Generate Makefiles
      # Build your program with the given configuration
      run: cmake .

    - name: Run tidy-check
      run: make tidy
